name: Extra Solar Planets
favicon: null
layout_spectrum: 0.99729
typography_spectrum: 0.9056305529084057
title: Extra Solar Planets
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#05060a'
    - '#323639'
    - '#696d78'
    - '#9195a0'
    - '#f9fdff'
  brandStrength: 0.5712571223266423
  lightness: 0.7656030817888677
  saturation: 0.8256692681461573
  rhythmicContrast: 0.010700064478442073
purpose: []
